apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: argocds.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: ArgoCD
    listKind: ArgoCDList
    plural: argocds
    singular: argocd
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            applicationController:
              properties:
                containerPort:
                  description: Container port for application controller server and
                    metrics
                  format: int64
                  type: integer
                image:
                  description: Describe a container image
                  properties:
                    pullPolicy:
                      description: Docker image pull policy
                      type: string
                    repository:
                      description: Docker image repo
                      type: string
                    tag:
                      description: Docker image tag
                      type: string
                  required:
                  - pullPolicy
                  - repository
                  - tag
                  type: object
                servicePort:
                  description: Service port for applicaiton controller server
                  format: int64
                  type: integer
                volumeMounts:
                  description: Additional volume mounts
                  items:
                    type: object
                  type: array
                volumes:
                  description: Additional volumes
                  items:
                    type: object
                  type: array
              required:
              - containerPort
              - servicePort
              - image
              type: object
            certificate:
              properties:
                enabled:
                  description: Enable certificate (requires cert-manager)
                  type: boolean
                issuer:
                  properties:
                    kind:
                      type: string
                    name:
                      type: string
                  required:
                  - kind
                  - name
                  type: object
              required:
              - enabled
              type: object
            clusterAdminAccess:
              properties:
                enabled:
                  description: Standard Argo CD installation with cluster-admin access.
                    Set this true if you plan to use Argo CD to deploy applications
                    in the same cluster that Argo CD runs in (i.e. kubernetes.svc.default).
                    Will still be able to deploy to external clusters with inputted
                    credentials.
                  type: boolean
              required:
              - enabled
              type: object
            config:
              properties:
                configManagementPlugins:
                  description: List of custom config management plugins
                  type: string
                createSecret:
                  description: Creates the argocd-secret secret, set to false to manage
                    externally
                  type: boolean
                dexConfig:
                  description: Configuration for external auth and URL
                  type: string
                enableAnonymousAccess:
                  type: boolean
                helmRepositories:
                  description: Configuration for external Helm charts
                  type: string
                instanceLabelKey:
                  description: Custom instance label key
                  type: string
                oidcConfig:
                  description: Configuration for OpenID connect
                  type: string
                repositories:
                  description: Configuration for remote Git repositories for Applications
                  type: string
                resourceCustomizations:
                  description: ResourceCustomizations can be used to create custom
                    health checks for resources
                  type: string
                resourceExclusions:
                  type: string
                url:
                  description: External URL for ArgoCD
                  type: string
                webhook:
                  properties:
                    bitbucketSecret:
                      description: BitBucket incoming webhook secret
                      type: string
                    githubSecret:
                      description: GitHub incoming webhook secret
                      type: string
                    gitlabSecret:
                      description: GitLab incoming webhook secret
                      type: string
                  type: object
              required:
              - createSecret
              - resourceExclusions
              - enableAnonymousAccess
              type: object
            dexServer:
              properties:
                containerPortGrpc:
                  description: Container port for Dex Server GRPC
                  format: int64
                  type: integer
                containerPortHttp:
                  description: Container port for Dex Server HTTP
                  format: int64
                  type: integer
                image:
                  description: Describe a container image
                  properties:
                    pullPolicy:
                      description: Docker image pull policy
                      type: string
                    repository:
                      description: Docker image repo
                      type: string
                    tag:
                      description: Docker image tag
                      type: string
                  required:
                  - pullPolicy
                  - repository
                  - tag
                  type: object
                initImage:
                  description: Describe a container image
                  properties:
                    pullPolicy:
                      description: Docker image pull policy
                      type: string
                    repository:
                      description: Docker image repo
                      type: string
                    tag:
                      description: Docker image tag
                      type: string
                  required:
                  - pullPolicy
                  - repository
                  - tag
                  type: object
                servicePortGrpc:
                  description: Service port for Dex Server GRPC
                  format: int64
                  type: integer
                servicePortHttp:
                  description: Service port for Dex Server HTTP
                  format: int64
                  type: integer
                volumeMounts:
                  description: Additional volume mounts
                  items:
                    type: object
                  type: array
                volumes:
                  description: Additional volumes
                  items:
                    type: object
                  type: array
              required:
              - containerPortHttp
              - containerPortGrpc
              - servicePortHttp
              - servicePortGrpc
              - image
              - initImage
              type: object
            ingress:
              properties:
                additionalHosts:
                  description: Ingress additional hosts
                  items:
                    type: string
                  type: array
                anntotations:
                  additionalProperties:
                    type: string
                  description: Annotations for ingress object
                  type: object
                enabled:
                  description: Enable ingress
                  type: boolean
                path:
                  type: string
                tls:
                  additionalProperties:
                    type: string
                  description: Ingress TLS configuration
                  type: object
              required:
              - enabled
              - path
              type: object
            rbac:
              properties:
                policyCvs:
                  description: RBAC policy in CSV
                  type: string
                policyDefault:
                  description: 'The default role Argo CD will fall back to, when authorizing
                    API requests, ie: role:readonly'
                  type: string
                scopes:
                  description: 'Scopes controls which OIDC scopes to examine during
                    rbac enforcement (in addition to sub scope). ie: [groups]'
                  type: string
              type: object
            redis:
              properties:
                containerPort:
                  description: Container port for Redis
                  format: int64
                  type: integer
                image:
                  description: Describe a container image
                  properties:
                    pullPolicy:
                      description: Docker image pull policy
                      type: string
                    repository:
                      description: Docker image repo
                      type: string
                    tag:
                      description: Docker image tag
                      type: string
                  required:
                  - pullPolicy
                  - repository
                  - tag
                  type: object
                servicePort:
                  description: Service port for Redis
                  format: int64
                  type: integer
              required:
              - containerPort
              - servicePort
              - image
              type: object
            repoServer:
              properties:
                containerPort:
                  description: Container port for repo server
                  format: int64
                  type: integer
                image:
                  description: Describe a container image
                  properties:
                    pullPolicy:
                      description: Docker image pull policy
                      type: string
                    repository:
                      description: Docker image repo
                      type: string
                    tag:
                      description: Docker image tag
                      type: string
                  required:
                  - pullPolicy
                  - repository
                  - tag
                  type: object
                servicePort:
                  description: Service port for repo server
                  format: int64
                  type: integer
                volumeMounts:
                  description: Additional volume mounts
                  items:
                    type: object
                  type: array
                volumes:
                  description: Additional volumes
                  items:
                    type: object
                  type: array
              required:
              - containerPort
              - servicePort
              - image
              type: object
            server:
              properties:
                anntotations:
                  additionalProperties:
                    type: string
                  description: Annotations for the server deployment
                  type: object
                containerPort:
                  description: Container port for server
                  format: int64
                  type: integer
                extraArgs:
                  description: Add additional arguments
                  items:
                    type: string
                  type: array
                image:
                  description: Describe a container image
                  properties:
                    pullPolicy:
                      description: Docker image pull policy
                      type: string
                    repository:
                      description: Docker image repo
                      type: string
                    tag:
                      description: Docker image tag
                      type: string
                  required:
                  - pullPolicy
                  - repository
                  - tag
                  type: object
                metricsPort:
                  description: Container port for server metrics
                  format: int64
                  type: integer
                serviceAnnotations:
                  additionalProperties:
                    type: string
                  description: Annotations for server service
                  type: object
                servicePortHttp:
                  description: HTTP Container port for server
                  format: int64
                  type: integer
                servicePortHttps:
                  description: HTTPS Container port for server
                  format: int64
                  type: integer
                serviceType:
                  description: Service Type string describes ingress methods for a
                    service
                  type: string
                volumeMounts:
                  description: Additional volume mounts
                  items:
                    type: object
                  type: array
                volumes:
                  description: Additional volumes
                  items:
                    type: object
                  type: array
              required:
              - containerPort
              - metricsPort
              - servicePortHttp
              - servicePortHttps
              - image
              - serviceType
              type: object
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
